name = "govi-dashboard"
compatibility_date = "2025-08-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "govi-dashboard"
database_id = "226da33a-fe7b-4159-bde8-235b7cd5b071"
